spring:
  application:
    name: pmanager
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080
  servlet:
    context-path: /
app:
  pageSize: 3


